name: NEOVERSE
favicon: null
layout_spectrum: 0.8949387546163052
typography_spectrum: 0.5533070482779294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2262792366091162
  lightness: 0.8469031855929643
  saturation: 0.5486375645268708
  rhythmicContrast: 0.02757839346304536
purpose: []
