name: NEOVERSE
favicon: null
layout_spectrum: 0.4795750055927783
typography_spectrum: 0.7620255120564252
title: Matter of Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.4233164871111512
  lightness: 0.4768003092613071
  saturation: 0.665079259313643
  rhythmicContrast: 0.3356961908284575
purpose: []
