name: NEOVERSE
favicon: null
layout_spectrum: 0.75186
typography_spectrum: 0.64745
title: Matter of Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090601'
    - '#1c1e33'
    - '#463929'
    - '#fefefc'
    - '#8f784f'
  brandStrength: 0.5
  lightness: 0.8469031855929643
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
