name: NEOVERSE
favicon: null
layout_spectrum: 0.8949387546163052
typography_spectrum: 0.64745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#feffef'
    - '#f80300'
    - '#6e4d23'
    - '#c1d5c0'
  brandStrength: 0.5
  lightness: 0.8469031855929643
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
